### PR TITLE
generated models ram and build

### PR DESCRIPTION
**Pull request by DanielCadiz**
## The Story
-generated model ram
-generated model build

### CODE REVIEW

**Review by AdrianIlaga — COMMENTED** [review]
LGTM

**Review by EliezerAmbion — COMMENTED** [review]
Looks good

**Review by analyn-cajocson — APPROVED** [review]

**Comment by jarencudilla** [comment]
Nice, Good job, sir.

**Comment by jarencudilla** [comment]
Good job, thank you the modifications.

**Review by jarencudilla — COMMENTED** [review]
Nice, Good job, thanks for this.

**Pull request merged**
